name: CI
on: [push, workflow_dispatch] # Allows you to run this workflow manually from the Actions tab
jobs:
  test-like-a-jest:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH"
      - run: bun test
  api-file:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH"
      - run: bun api-file/main.ts
  hello-github-path:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: echo "${{ needs.bun.outputs.BUN_BIN }}" >> "$GITHUB_PATH"
      - run: bun --help
      - run: bun hello-world/app.ts
  hello-github-env:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: echo "PATH=${{ needs.bun.outputs.BUN_BIN }}:$PATH" >> "$GITHUB_ENV"
      - run: bun --help
      - run: bun hello-world/app.ts
  hello-bash-variable:
    needs: bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            !~/.m2
            ~/.bun
            ~/.npm
            ~/.node
          key: ${{ runner.os }}-${{ hashFiles('**/workflows/*.yml', '**/package.json', '**/package-lock.json') }}
      - run: PATH="$HOME/.bun/bin:$PATH" bun --help
      - run: PATH="$HOME/.bun/bin:$PATH" bun hello-world/app.ts
  bun:
    uses: ./.github/workflows/bun.yml
