name: CI
on: [push, workflow_dispatch] # Allows you to run this workflow manually from the Actions tab
jobs:
  tests:
    name: run-ts-file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.bun
            !~/.m2
          key: ${{ runner.os }}-${{ hashFiles('**/ci.yml', '**/package.json', '**/package-lock.json') }}
      - run: curl https://bun.sh/install | bash
      - run: PATH="$HOME/.bun/bin:$PATH" bun --help
      - run: PATH="$HOME/.bun/bin:$PATH" bun app.ts
